# Generated by Django 5.2 on 2025-04-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patientprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecinprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
